version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "80:5000"
    links:
      - mongo
      - redis
    command: npm start

  mongo:
    container_name: db-mongo
    image: mongo
    ports:
      - "27017:27017"

  redis:
    container_name: db-redis
    image: redis
    ports:
      - "6379:6379"
